version: "0.5"

processes:
  postgres:
    command: podman run --rm --name lay-postgres-dev -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=devpassword123 -e POSTGRES_DB=backend -p 55432:5432 docker.io/library/postgres:16
    availability:
      restart: on_failure
    readiness_probe:
      exec:
        command: "podman exec lay-postgres-dev pg_isready -U postgres"
      initial_delay_seconds: 5
      period_seconds: 5
      timeout_seconds: 3
      success_threshold: 1

  adminer:
    command: podman run --rm --name lay-adminer-dev -p 58080:8080 -e ADMINER_SERVER=host.containers.internal:55432 -e ADMINER_DB=backend -e ADMINER_USERNAME=postgres -e ADMINER_PASSWORD=devpassword123 -e ADMINER_DRIVER=pgsql -e ADMINER_AUTOLOGIN=1 -e ADMINER_NAME="Lay Development DB" docker.io/michalhosna/adminer:latest
    depends_on:
      postgres:
        condition: process_healthy
    availability:
      restart: on_failure

  backend:
    command: cargo watch -w src -w $(git rev-parse --show-toplevel)/.env -x run
    working_dir: ./backend
    environment:
      - "DATABASE_URL=postgres://postgres:devpassword123@localhost:55432/backend"
      - "HOST=0.0.0.0"
      - "PORT=3000"
      - "RUST_LOG=info,backend=debug"
      - "SES_FROM_EMAIL=${SES_FROM_EMAIL}"
      - "SES_REPLY_TO_EMAIL=${SES_REPLY_TO_EMAIL}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "AWS_REGION=${AWS_REGION:-us-east-1}"
      - "AWS_PROFILE=${AWS_PROFILE}"
      - "OPENSSL_DIR=${OPENSSL_DIR}"
      - "OPENSSL_LIB_DIR=${OPENSSL_LIB_DIR}"
      - "OPENSSL_INCLUDE_DIR=${OPENSSL_INCLUDE_DIR}"
      - "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}"
    depends_on:
      postgres:
        condition: process_healthy
    availability:
      restart: on_failure

  cli:
    command: cargo watch -x 'build --release'
    working_dir: ./cli
    environment:
      - "OPENSSL_DIR=${OPENSSL_DIR}"
      - "OPENSSL_LIB_DIR=${OPENSSL_LIB_DIR}"
      - "OPENSSL_INCLUDE_DIR=${OPENSSL_INCLUDE_DIR}"
      - "PKG_CONFIG_PATH=${PKG_CONFIG_PATH}"
    availability:
      restart: on_failure
